# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  checkout:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.7.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: metabase-athena-driver
      - run:
          name: Checkout Metabase source
          command: git clone --depth=1 -b $BRANCH https://github.com/metabase/metabase.git metabase
      - run:
          name: Link driver module
          command: ln -sfv ../../../metabase-athena-driver metabase/modules/drivers/athena
      # Download and cache dependencies
      - restore_cache:
          key: metabase-athena-driver-{{ checksum "metabase-athena-driver/project.clj" }}
      - run:
          name: Download Athena driver
          command: |
            mkdir -p ~/.m2/repository/athena/athena-jdbc/2.0.7/
            wget -O ~/.m2/repository/athena/athena-jdbc/2.0.7/athena-jdbc-2.0.7.jar https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.7/AthenaJDBC42_2.0.7.jar
      - run:
          working_directory: metabase-athena-driver
          command: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: metabase-athena-driver-{{ checksum "metabase-athena-driver/project.clj" }}
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - project/metabase-athena-driver
            - project/metabase
            - .m2
  test:
    docker:
      - image: circleci/clojure:lein-2.7.1
    steps:
      - attach_workspace:
          at: /home/circleci/
      # run tests!
      - run:
          name: Athena unit tests
          working_directory: metabase-athena-driver
          command: lein test
  
  test-metabase-driver:
    docker:
      - image: circleci/clojure:lein-2.7.1
    steps:
      - attach_workspace:
          at: /home/circleci/
      - run:
          name: Metabase driver integration tests
          working_directory: metabase
          environment:
            DRIVERS: h2,athena
          command: lein with-profile +ci test

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - test-metabase-driver:
          requires:
            - checkout
